# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Blackcat Informatics® Inc.

"""Dataclasses capturing structured CLI inputs for the lint command."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ...core.lint_literals import (
    BanditLevelLiteral,
    OutputModeLiteral,
    PRSummarySeverityLiteral,
    SensitivityLiteral,
    StrictnessLiteral,
)
from ...core.options import (
    ExecutionRuntimeOptions,
    LintDisplayToggles,
    LintGitOptions,
    LintSelectionOptions,
    LintSeverityOptions,
)


@dataclass(slots=True)
class LintPathParams:
    """Capture filesystem path arguments supplied to the CLI."""

    paths: list[Path]
    root: Path
    paths_from_stdin: bool
    dirs: list[Path]
    exclude: list[Path]


LintGitParams = LintGitOptions
LintSelectionParams = LintSelectionOptions
LintExecutionRuntimeParams = ExecutionRuntimeOptions


@dataclass(slots=True)
class LintOutputParams(LintDisplayToggles):
    """Rendering preferences for user-facing output."""

    def as_dict(self) -> dict[str, bool | OutputModeLiteral]:
        """Return the toggles as a serialisable dictionary."""

        return {
            "verbose": self.verbose,
            "quiet": self.quiet,
            "no_color": self.no_color,
            "no_emoji": self.no_emoji,
            "output_mode": self.output_mode,
        }

    def with_output_mode(self, output_mode: OutputModeLiteral) -> LintOutputParams:
        """Return a copy of the toggles with an updated output mode.

        Args:
            output_mode: Output mode literal requested by the caller.

        Returns:
            LintOutputParams: New instance reflecting the provided
            ``output_mode`` value.
        """

        return LintOutputParams(
            verbose=self.verbose,
            quiet=self.quiet,
            no_color=self.no_color,
            no_emoji=self.no_emoji,
            output_mode=output_mode,
        )


@dataclass(slots=True)
class LintReportingParams:
    """Reporting targets selected by the user."""

    show_passing: bool
    no_stats: bool
    report_json: Path | None
    sarif_out: Path | None
    pr_summary_out: Path | None


@dataclass(slots=True)
class LintSummaryParams:
    """Parameters controlling PR summary generation."""

    pr_summary_limit: int
    pr_summary_min_severity: PRSummarySeverityLiteral
    pr_summary_template: str
    advice: bool


@dataclass(slots=True)
class LintOverrideParams:
    """Shared override knobs applied to tool configurations."""

    line_length: int
    sql_dialect: str
    max_complexity: int | None
    max_arguments: int | None
    type_checking: StrictnessLiteral | None
    python_version: str | None


@dataclass(slots=True)
class LintSeverityParams(LintSeverityOptions):
    """Typed severity overrides returned by CLI dependencies."""

    def as_tuple(
        self,
    ) -> tuple[BanditLevelLiteral | None, BanditLevelLiteral | None, float | None, SensitivityLiteral | None]:
        """Return severity override values as a tuple.

        Returns:
            tuple[BanditLevelLiteral | None, BanditLevelLiteral | None, float | None, SensitivityLiteral | None]:
            Tuple capturing the severity overrides for Bandit, pylint, and
            sensitivity adjustments.
        """

        return (
            self.bandit_severity,
            self.bandit_confidence,
            self.pylint_fail_under,
            self.sensitivity,
        )


@dataclass(slots=True)
class LintMetaParams:
    """Meta toggles that alter command execution flow."""

    doctor: bool
    tool_info: str | None
    fetch_all_tools: bool
    validate_schema: bool
    normal: bool
    check_docstrings: bool
    check_suppressions: bool
    check_types_strict: bool
    check_closures: bool
    check_signatures: bool
    check_cache_usage: bool


@dataclass(slots=True)
class LintTargetGroup:
    """Group path discovery parameters with git selectors."""

    path: LintPathParams
    git: LintGitParams


@dataclass(slots=True)
class LintExecutionGroup:
    """Group tool selection and runtime execution options."""

    selection: LintSelectionParams
    runtime: LintExecutionRuntimeParams


@dataclass(slots=True)
class LintOutputGroup:
    """Combine rendering, reporting, and summary preferences."""

    rendering: LintOutputParams
    reporting: LintReportingParams
    summary: LintSummaryParams


@dataclass(slots=True)
class LintAdvancedGroup:
    """Aggregate advanced overrides and meta controls."""

    overrides: LintOverrideParams
    severity: LintSeverityParams
    meta: LintMetaParams


@dataclass(slots=True)
class LintCLIInputs:
    """Top-level container for structured CLI inputs."""

    targets: LintTargetGroup
    execution: LintExecutionGroup
    output: LintOutputGroup
    advanced: LintAdvancedGroup


@dataclass(slots=True)
class LintOutputArtifacts:
    """Filesystem artifacts generated by the lint command."""

    report_json: Path | None
    sarif_out: Path | None
    pr_summary_out: Path | None


@dataclass(slots=True)
class RuntimeConcurrencyParams:
    """CLI inputs related to parallelism and local linter usage."""

    jobs: int | None
    bail: bool
    use_local_linters: bool


@dataclass(slots=True)
class RuntimeCacheParams:
    """CLI inputs describing cache toggles and locations."""

    no_cache: bool
    cache_dir: Path


@dataclass(slots=True)
class OverrideFormattingParams:
    """Command-line inputs affecting formatting defaults."""

    line_length: int
    sql_dialect: str
    python_version: str | None


@dataclass(slots=True)
class OverrideThresholdParams:
    """Command-line thresholds for shared complexity limits."""

    max_complexity: int | None
    max_arguments: int | None


@dataclass(slots=True)
class OverrideStrictnessParams:
    """Command-line strictness overrides for type checking."""

    type_checking: StrictnessLiteral | None


__all__ = (
    "BanditLevelLiteral",
    "LintAdvancedGroup",
    "LintCLIInputs",
    "LintExecutionGroup",
    "LintExecutionRuntimeParams",
    "LintGitParams",
    "LintMetaParams",
    "LintOutputArtifacts",
    "LintOutputGroup",
    "LintOutputParams",
    "LintOverrideParams",
    "LintPathParams",
    "LintReportingParams",
    "LintSelectionParams",
    "LintSeverityParams",
    "LintSummaryParams",
    "LintTargetGroup",
    "OutputModeLiteral",
    "PRSummarySeverityLiteral",
    "RuntimeCacheParams",
    "RuntimeConcurrencyParams",
    "OverrideFormattingParams",
    "OverrideThresholdParams",
    "OverrideStrictnessParams",
    "SensitivityLiteral",
    "StrictnessLiteral",
)
