# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Blackcat Informatics® Inc.

"""Core service interfaces shared across the project."""

from __future__ import annotations

import logging
from abc import abstractmethod
from typing import Protocol, runtime_checkable

from rich.console import Console

type JsonScalar = str | int | float | bool | None
type JsonValue = JsonScalar | list[JsonValue] | dict[str, JsonValue]


@runtime_checkable
class ConsoleFactory(Protocol):
    """Provide a factory that returns console instances honouring colour/emoji settings."""

    @property
    @abstractmethod
    def default_color(self) -> bool:
        """Return whether colour output is enabled by default.

        Returns:
            bool: ``True`` when colour output should be enabled automatically.
        """

        raise NotImplementedError

    @abstractmethod
    def __call__(self, *, color: bool, emoji: bool) -> Console:
        """Create a console-like object supporting ``print``.

        Args:
            color: Flag indicating whether colour output is desired.
            emoji: Flag indicating whether emoji output is desired.

        Returns:
            Console: Console instance matching the requested preferences.
        """
        raise NotImplementedError


@runtime_checkable
class ConsoleManager(Protocol):
    """Manage console instances keyed by output preferences."""

    @property
    @abstractmethod
    def managed_presets(self) -> tuple[bool, bool]:
        """Return the default ``(color, emoji)`` tuple managed by the service.

        Returns:
            tuple[bool, bool]: Preferred defaults for colour and emoji output.
        """
        raise NotImplementedError

    @abstractmethod
    def get(self, *, color: bool, emoji: bool) -> Console:
        """Return a console configured according to the requested options.

        Args:
            color: Indicates whether colour output should be enabled.
            emoji: Indicates whether emoji output should be enabled.

        Returns:
            Console: Console instance matching the caller's request.
        """
        raise NotImplementedError


@runtime_checkable
class LoggerFactory(Protocol):
    """Provide a factory that returns structured loggers."""

    @property
    @abstractmethod
    def namespace(self) -> str:
        """Return the logger namespace produced by the factory.

        Returns:
            str: Namespace prefix applied to emitted logger instances.
        """
        raise NotImplementedError

    @abstractmethod
    def __call__(self, name: str) -> logging.Logger:
        """Return a logger identified by ``name``.

        Args:
            name: Logger identifier requested by the caller.

        Returns:
            logging.Logger: Configured logger instance.
        """
        raise NotImplementedError


@runtime_checkable
class Serializer(Protocol):
    """Serialize/deserialize model instances."""

    @property
    @abstractmethod
    def content_type(self) -> str:
        """Return the MIME type generated by the serializer.

        Returns:
            str: MIME type of the serialised representation.
        """
        raise NotImplementedError

    @abstractmethod
    def dump(self, value: JsonValue) -> str:
        """Return the serialized representation of ``value``.

        Args:
            value: JSON-compatible payload to serialize.

        Returns:
            str: Serialized representation of ``value``.
        """
        raise NotImplementedError

    @abstractmethod
    def load(self, payload: str) -> JsonValue:
        """Return a model instance deserialized from ``payload``.

        Args:
            payload: Serialized representation produced by :meth:`dump`.

        Returns:
            JsonValue: Reconstructed payload.
        """
        raise NotImplementedError


@runtime_checkable
class AnsiFormatter(Protocol):
    """Apply ANSI and emoji formatting to text."""

    @property
    @abstractmethod
    def supports_emoji(self) -> bool:
        """Return whether emoji formatting is supported.

        Returns:
            bool: ``True`` when emoji transformations are supported.
        """
        raise NotImplementedError

    @abstractmethod
    def colorize(self, text: str, code: str, enable: bool) -> str:
        """Return ``text`` wrapped in colour codes when ``enable`` is true.

        Args:
            text: Source text to colourize.
            code: ANSI code applied when colouring.
            enable: Flag indicating whether colouring is active.

        Returns:
            str: Potentially colourised text.
        """
        raise NotImplementedError

    @abstractmethod
    def emoji(self, symbol: str, enable: bool) -> str:
        """Return ``symbol`` when emoji output is enabled.

        Args:
            symbol: Emoji symbol to render.
            enable: Flag indicating whether emoji output is enabled.

        Returns:
            str: Emoji symbol when enabled, otherwise an empty string.
        """
        raise NotImplementedError


__all__ = [
    "AnsiFormatter",
    "ConsoleFactory",
    "ConsoleManager",
    "LoggerFactory",
    "Serializer",
]
