# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Blackcat Informatics® Inc.

"""Core service interfaces shared across the project."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ConsoleFactory(Protocol):
    """Factory returning console instances honouring colour/emoji settings."""

    @property
    def default_color(self) -> bool:
        """Return whether colour output is enabled by default."""
        raise NotImplementedError("ConsoleFactory.default_color must be implemented")

    def __call__(self, *, color: bool, emoji: bool) -> Any:
        """Return a console-like object supporting ``print``."""

        raise NotImplementedError


@runtime_checkable
class ConsoleManager(Protocol):
    """Manage console instances keyed by output preferences."""

    @property
    def managed_presets(self) -> tuple[bool, bool]:
        """Return the default ``(color, emoji)`` tuple managed by the service."""
        raise NotImplementedError("ConsoleManager.managed_presets must be implemented")

    def get(self, *, color: bool, emoji: bool) -> Any:
        """Return a console configured according to the requested options."""

        raise NotImplementedError


@runtime_checkable
class LoggerFactory(Protocol):
    """Factory returning structured loggers."""

    @property
    def namespace(self) -> str:
        """Return the logger namespace produced by the factory."""
        raise NotImplementedError("LoggerFactory.namespace must be implemented")

    def __call__(self, name: str) -> Any:
        """Return a logger identified by ``name``."""

        raise NotImplementedError


@runtime_checkable
class Serializer(Protocol):
    """Serialize/deserialize model instances."""

    @property
    def content_type(self) -> str:
        """Return the MIME type generated by the serializer."""
        raise NotImplementedError("Serializer.content_type must be implemented")

    def dump(self, value: Any) -> str:
        """Return the serialized representation of ``value``."""

        raise NotImplementedError

    def load(self, payload: str) -> Any:
        """Return a model instance deserialized from ``payload``."""

        raise NotImplementedError


@runtime_checkable
class AnsiFormatter(Protocol):
    """Apply ANSI and emoji formatting to text."""

    @property
    def supports_emoji(self) -> bool:
        """Return whether emoji formatting is supported."""
        raise NotImplementedError("AnsiFormatter.supports_emoji must be implemented")

    def colorize(self, text: str, code: str, enable: bool) -> str:
        """Return ``text`` wrapped in colour codes when ``enable`` is true."""

        raise NotImplementedError

    def emoji(self, symbol: str, enable: bool) -> str:
        """Return ``symbol`` when emoji output is enabled."""

        raise NotImplementedError


__all__ = [
    "AnsiFormatter",
    "ConsoleFactory",
    "ConsoleManager",
    "LoggerFactory",
    "Serializer",
]
